### ISSUE TITLE
styling not correct when used within Bootstrap .form-horizontal

### ISSUE THREAD

**Issue by TomekSzymanski** [kleinejan/titatoggle#5]
When used in plain Bootstrap form, everything is fine:
```html
<form>
        <div class="checkbox checkbox-slider--default">
            <label>
                <input type="checkbox"><span>TiTaToggle</span>
            </label>
        </div>
    </form>
```

When used within form-horizontal:
```html
<form class="form-horizontal">
        <div class="checkbox checkbox-slider--default">
            <label>
                <input type="checkbox"><span>TiTaToggle</span>
            </label>
        </div>
    </form>
```
then, because of this Bootstrap css rule, and this property: `padding-top: 7px`:
```css
.form-horizontal .radio,
.form-horizontal .checkbox,
.form-horizontal .radio-inline,
.form-horizontal .checkbox-inline {
  padding-top: 7px;
  margin-top: 0;
  margin-bottom: 0;
}
```
the handle and its container are not top aligned - the container is pushed down, but not the handle.

A way to correct, for my limited css knowledge, may be to add  `margin-top: 7px;` to this rule
```css
.checkbox-slider--default input + span:after {
  background: #ffffff;
  border: solid transparent 1px;
  background-clip: content-box;
}
```
and all other rules like this one.

Regards and thanks for great component!
Tomasz
